spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reactive_user
    username: postgres
    password: 1234
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
      properties:
        format_sql: true
      show-sql: true
